# IMPORTS

import numpy as onp
import jax.numpy as np
import jax
from jax import random
from jax import jit
from jax import vmap
from jax import lax
from jax import config
config.update("jax_enable_x64", True)

from jax_md import space, smap, energy, minimize, quantity, simulate, partition, util
from jax_md.util import f32

from collections import namedtuple

vectorize = np.vectorize

from functools import partial

from .utils import bearing_angle, ttc_tot

# BEARING ANGLE

def bearing_angle_tot(pos, V, R, displacement) -> jax.Array[jax.Array[jax.Array[jax.Array[float]]]]:
    """
    JAX-compatible function that returns the bearing angle between all pedestrians in a system.
    Bearing angles for each pair of pedestrians are returned in an array of shape (3, ), with array[0]
    being the center angle, and array[1:] being the boundary angles.
    The bearing angle of a person with themselves is defined to be pi.

    Arguments:
        pos (ArrayLike): input position array of shape (N, 2)
        V (ArrayLike): input velocity array of shape (N, 2)
        R (float/int): scalar radius of pedestrians.
        displacement (DisplacementFn): displacement function, generated by jax_md.space

    Returns:
        An array of bearing angles between all pairs of pedestrians, of shape (N, N, 3, 1).
    """
    dpos = space.map_product(displacement)(pos, pos)
    return vmap(vmap(bearing_angle, (0, None, None)), (0, 0, None))(dpos, V, R)

# VISION INTERACTION FUNCTIONS:

def identity_visual_interaction(angle, limit_angle):
    return np.where(np.abs(angle) < limit_angle, 1, 0)

def identity_visual_interaction_tot(angles, limit_angle=np.pi/2) -> jax.Array[jax.Array[jax.Array[float]]]:
    """Returns matrix whose entries [i, j, 0] are 1 if person j is in person i's FOV, 0 otherwise"""
    return identity_visual_interaction(angles[:, :, 0, :], limit_angle)

# VISION GRAPHING:

def vision_graph(pos, V, R, displacement, visual_action, threshold=3, **kwargs):
    """
    Returns matrix whose entries [i, j, 0] are 0 if person j is not visually registered by person i, nonzero otherwise.
    "Visually registered" means that the visual interaction is above a certain threshold value.
    """
    param = visual_action(bearing_angle_tot(pos, V, R, displacement), **kwargs) / ttc_tot(pos, V, R, displacement, **kwargs)
    filtered_param = np.where(param < 1/threshold, 0, param)

    return filtered_param
